# Utilisez la commande ss dans workstation1 pour afficher toutes les
# connexions TCP actives, les connexions UDP et les sockets en écoute
# uniquement.
---
- name: capture des connection tcp 
  command: ss -t
  register: tcp_outputs

- name: capture des connection udp
  command: ss -u
  register: udp_outputs

- name: sockets en ecoute 
  command: ss -a
  register: sockets_outputs


- name: Display TCP connection results
  debug:
    var: tcp_outputs.stdout_lines

- name: Display UDP connection results
  debug:
    var: udp_outputs.stdout_lines  

- name: Display SOCKETS connection results
  debug:
    var: sockets_outputs.stdout_lines

    