
# 1. Installez iperf3 dans workstation1 et workstation2.
# ok dans le docker file 


# 2-Configurez workstation1 comme serveur iperf3 et workstation2
# comme client, puis exécutez un test de bande passante.

---
- name: define iperf3_client
  become: yes
  command:  
